### PR TITLE
Update args for fuelup v0.2.0

### LINKED ISSUE #24: Update arg once fuelup toolchains are ready
(Currently blocked by https://github.com/FuelLabs/fuelup/pull/73)

Once https://github.com/FuelLabs/fuelup/pull/73 is merged in, `fuelup install` will no longer be a valid command - this will now be `fuelup toolchain install <toolchain>`, where __toolchain__ is now `latest`, and in the future should support `nightly` and `stable` as well. Which means the arg passed [here](https://github.com/FuelLabs/action-fuel-toolchain/blob/e5f0ae2c6207d59feaca683b6eaf0515299213b1/src/fuelup.ts#L66-L68) should be updated to `toolchain install latest` once the PR above is merged in, and a new `fuelup` release is cut.

### PR DESCRIPTION
**Pull request by binggh**
Closes #24 

**Note: Only to be merged after `fuelup` v0.2.0 is released!**

https://github.com/FuelLabs/fuelup/pull/77 is about to be merged with a new release of `fuelup` supporting the toolchain pattern (similar to `rustup`), which means `fuelup install` is now an invalid command. 

The new command to install the _latest_ toolchain will be:

```sh
fuelup toolchain install latest
```

With support for `nightly` and `stable` later.

### CODE REVIEW

**Review by Braqzen — COMMENTED** [review]
So this one change in the typescript command made the entire transpiled `.js` file change instead of a couple of lines inside of it? That's strange and difficult to figure out.

`fuelup.ts` looks fine however given this comment I'll defer to someone else.

**Review by adlerjohn — APPROVED** [review]
This is fine. In a subsequent PR, we'll want this to be configured as parameters to the action.

**Comment by adlerjohn** [comment]
@binggh can you clarify why the `install_latest` would pass? The `toolchain` command doesn't exist in `v0.1.3`, no?

**Comment by binggh** [comment]
@adlerjohn ah, i think it's because earlier in the day i did cut a new release but cancelled it because I wanted to wait for this PR to be reviewed. Seems like the publish went through regardless: https://github.com/FuelLabs/fuelup/tree/gh-pages so the versioning there is v0.2.0 already

**Review by JoshuaBatty — APPROVED** [review]

**Comment by adlerjohn** [comment]
Looks like this doesn't pass CI now

**Comment by binggh** [comment]
> Looks like this doesn't pass CI now

Seems like it something wrong with `fuelup-init.sh` instead

**Pull request merged**
